# my global config
global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
scrape_configs:
  - job_name: exemple
    static_configs:
     - targets:
        - 192.168.33.10:8000

